### ISSUE TITLE
Problem getting proper types

### ISSUE THREAD

**Issue by debasishg** [scalastuff/scalabeans#1]
I have a class as ..

case class ContactWithOptionalAddr(name: String, addresses: Option[Map[String, Address]]) 

When I do a 

import org.scalastuff.scalabeans.Preamble._
val descriptor = descriptorOf[ContactWithOptionalAddr]
for (property <- descriptor.properties)
    println(property.name + ": " + property.scalaType)

I get ..

name: String
addresses: Option[Map[Tuple2[String,Address]]]

which is not correct .. the Tuple2 I mean .. help ?

**Comment by rditerwich** [comment]
Hi debasishg,

You are correct, it seems a bit odd. It stems from the fact that a
Map[K,V] extends form Iterable[Tuple2[K,V]]

So, the question is: how many type arguments does the addressesType
have (addressType.arguments.size)? 1 or 2?

We chose 1: the tuple containing the actual key van value types. This
is the only way to ensure compatibility with Iterable.

When matching a map type, you won't see this. Both of the following
case statements would match:

addressPropertyDesc.scalaType match {
  case IterableType(Tuple2Type(k, v)) =>
  case MapType(k, v) =>
}

I'm inclined just to change the toString of MapType. This would 'fix'
your example, but is entirely cosmetic...

Kind regards,

Ruud Diterwich

On Tue, May 17, 2011 at 9:25 AM, debasishg
reply@reply.github.com
wrote:
