### ISSUE TITLE
ScalaTypeCompiler.classInfoCache never gets GC'd

### ISSUE THREAD

**Issue by louoso** [scalastuff/scalabeans#4]
The weak key is an instance of ScalaType and the strong value is an instance of ClassInfo that refers to the same ScalaType instance so the keys are always strongly reachable via the value.

**Comment by advorkovyy** [comment]
You are right, the cache seems to be "strong" indeed. the reference to ScalaType from ClassInfo has to be removed.

Thanks!

**Comment by louoso** [comment]
Actually, after looking a bit longer, it seems .softValues would be more appropriate. Using weakKeys causes the cache to use object identity which results in a new entry for every ScalaType.

**Comment by louoso** [comment]
ClassDeclExtractor has a similar issue.

**Comment by sullis** [comment]
When will this fix appear in a released version of scalabeans?

**Comment by advorkovyy** [comment]
I plan it for the next week. I am busy now with new functionality, hope to finish it soon.

**Comment by advorkovyy** [comment]
Solved in 0.3

I've decided to make 0.3 a bugfix release. Just published it to Maven Central.
